### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ehsanbarkhordar**
The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jgmf-amazon** [comment]
We are checking `torchrun` on our end. Thanks!

**Comment by ehsanbarkhordar** [comment]
> We are checking `torchrun` on our end. Thanks!

**Comment by ehsanbarkhordar** [comment]
> We are checking `torchrun` on our end. Thanks!

‘torchrun’ has many advantages over ‘torch.distributed.launch’

For more info read [this](https://pytorch.org/docs/stable/elastic/run.html).

**Comment by jgmf-amazon** [comment]
Hi @ehsanbarkhordar , greetings. I had to make minor changes to support `torchrun`, namely to pick up the `LOCAL_RANK` environmental variable instead of only the `--local-rank` command line argument.

My apologies for superseding this PR (I actually thought it was an issue, not a PR), but I incorporated your readme changes in the latest `main` commit.

This is a good improvement. Thanks!

**Pull request closed without merging**
